In [1]:
import numpy as np

## Generate arrays


In [2]:
numList = [[3,0,6,11],[4,9,2,4],[2,9,9,1]]

In [3]:
arr = np.array (numList)

In [4]:
arr

array([[ 3,  0,  6, 11],
       [ 4,  9,  2,  4],
       [ 2,  9,  9,  1]])

In [5]:
arr.size

12

In [6]:
arr.dtype

dtype('int32')

In [7]:
arr.shape

(3, 4)

In [8]:
type (arr)

numpy.ndarray

In [9]:
arr.dtype

dtype('int32')

In [10]:
arr2 = np.arange(20)

In [11]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
arr3 = np.zeros(10)

In [13]:
arr3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
arr4 = np.ones(20)
arr4

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [15]:
arr = np.linspace(start = 10, stop = 100, num = 20)
arr

array([ 10.        ,  14.73684211,  19.47368421,  24.21052632,
        28.94736842,  33.68421053,  38.42105263,  43.15789474,
        47.89473684,  52.63157895,  57.36842105,  62.10526316,
        66.84210526,  71.57894737,  76.31578947,  81.05263158,
        85.78947368,  90.52631579,  95.26315789, 100.        ])

# Array methods

In [16]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
arr2 = np.append(arr2, 40)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 40])

In [19]:
arr2.dtype

dtype('int32')

In [20]:
type(arr2)

numpy.ndarray

In [21]:
arr2 = np.delete(arr2,17)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       18, 19, 40])

In [22]:
np.sort(arr)

array([ 10.        ,  14.73684211,  19.47368421,  24.21052632,
        28.94736842,  33.68421053,  38.42105263,  43.15789474,
        47.89473684,  52.63157895,  57.36842105,  62.10526316,
        66.84210526,  71.57894737,  76.31578947,  81.05263158,
        85.78947368,  90.52631579,  95.26315789, 100.        ])

In [27]:
arr = np.reshape(arr,(10,2))
arr

array([[ 10.        ,  14.73684211],
       [ 19.47368421,  24.21052632],
       [ 28.94736842,  33.68421053],
       [ 38.42105263,  43.15789474],
       [ 47.89473684,  52.63157895],
       [ 57.36842105,  62.10526316],
       [ 66.84210526,  71.57894737],
       [ 76.31578947,  81.05263158],
       [ 85.78947368,  90.52631579],
       [ 95.26315789, 100.        ]])

In [30]:
arr[5,1]

62.10526315789473

In [31]:
arr[9,1]

100.0

In [32]:
arr[1]

array([19.47368421, 24.21052632])

In [4]:
numArray = np.array([[5,7,8],[12,7,0]])
numArray

array([[ 5,  7,  8],
       [12,  7,  0]])

In [5]:
numArray[0]

array([5, 7, 8])

In [6]:
numArray[0,0:2]

array([5, 7])

In [7]:
numArray[0,-1]

8

In [8]:
numArray[-1,-2]

7

In [9]:
numArray[-1,-3]

12

In [10]:
numArray= np.array([[3,5,6],[5,7,0],[4,4,1],[5,2,9]])
numArray

array([[3, 5, 6],
       [5, 7, 0],
       [4, 4, 1],
       [5, 2, 9]])

In [20]:
numArray [1:3,0:2]

array([[5, 7],
       [4, 4]])

In [22]:
numArray [-2:-4,-2:-4]

array([], shape=(0, 0), dtype=int32)

In [18]:
numArray [1:3,0:2]

array([[5, 7],
       [4, 4]])